name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm run build

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
